services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=brzhk
      - APP_DB_PASS=bauka2003
      - APP_DB_NAME=techclone
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432